### ISSUE TITLE
FFserver sartet nicht

### ISSUE THREAD

**Issue by sseidl84** [mschlenstedt/LoxBerry-Plugin-CamStream4Lox#10]
FFserver lässt sich nicht sarten somit unbrauchbar

**Comment by mschlenstedt** [comment]
Log?! Was soll ich jetzt mit so einer Aussage anfangen? Du schreibst nicht einmal welche LoxBerry Version.

So kann ich nicht helfen...

**Comment by sseidl84** [comment]
Log welches Log?

wird nicht gefordert ?
außerdem warum sollte ich ÖFFENTLICH nen Log mit möglicherweise persönlichen Daten einstellen ?

und etwasfreundlicher ging das auch, wohl nen schlechten Tag....

LoxBerry V2.0.0.2
Cam Stream 1.0.0

**Comment by mschlenstedt** [comment]
Was willst Du denn jetzt von mir? Schreibst hier, dass das alles unbrauchbar ist, gibst keine weiteren Informationen, ich soll das in meienr Freizeit alles für Dich fixen und lesen kannst Du anscheinend auch nicht?!

https://www.loxforum.com/forum/projektforen/loxberry/plugins/218137-camstream4lox-v1-0-0#post218137

Mit einem schlechten Tag hat das nichts zu tun.

**Comment by sseidl84** [comment]
Ich nutze mal meine magische Glaskugel und suche unter den 4 Gruppen Lan Logs 
welchen verdammten willst du ??

mal den hier Raus 

Gruppe 'Ffserver_run'
 INFO: LoxBerry Version 2.0.0.2 ( is_raspberry.cfg )
 INFO: CamStream4Lox Version 1.0.0
 INFO: Loglevel: 3
/opt/loxberry/bin/plugins/camstream4lox/ffserver.sh: line 75: ffserver: command not found
 01.11.2019 09:36:13 TASK FINISHED
ohne dass ich jetz tier rein geh sag ich einfach das plugin installiert ffserver nicht und kanns daher nciht ausfühern

**Comment by sseidl84** [comment]
dann muss man das Plugin als EOL kennzeichen und nicht als Stable
somit weiß jeder bescheid dass es nicht läuft

**Comment by mschlenstedt** [comment]
Ich muss gar nichts. Und Tschüß.
