### ISSUE TITLE
vlc plug-in not starting

### ISSUE THREAD

**Issue by MB-Lox** [mschlenstedt/LoxBerry-Plugin-CamStream4Lox#20]
Hi, thanks for the efforts so far. Anyone aware how to resolve below issue? Several restarts and reinstalls did not resolve the issue. 

HW: raspi 4, 8 GB 

14.06.2021 08:13:53 TASK STARTED
 INFO: LoxBerry Version 2.2.0.4 ( is_raspberry.cfg )
 INFO: CamStream4Lox Version 2.0.1
 INFO: Loglevel: 3
 ERROR: VLC could not be started.
 14.06.2021 08:13:55 TASK FINISHED

**Comment by MB-Lox** [comment]
same like issue #19 , just got confused by the headline... 
Only difference is using a RasPi 4

**Comment by MB-Lox** [comment]
after configuration of cam settings and several attempts to restart it works no.
thanks

**Comment by nowonoc** [comment]
same issue here, same error log. over night the issue appears. no changes in config. can't start VLC anymore. any idea and solution?
