### ISSUE TITLE
FFmpeg: läuft nicht

### ISSUE THREAD

**Issue by Tommes78** [mschlenstedt/LoxBerry-Plugin-CamStream4Lox#6]
FFmpeg läuft nicht, aber FFmpeg ist installiert. Habe den FFserver mehrfach durchgesartet, kein Erfolg. 

Es scheint so das der Stream demnach nicht nach MJPEG konvertiert wird, da der Stream sich auch nicht anzeigen lässt.

**Comment by mschlenstedt** [comment]
So schlecht nachzuvollziehen. Da FFServer ab LoxBerry 2.0 (Debian Buster) nicht mehr unterstützt wird, erfolgt keine Fehlerbehebnung mehr. Sorry.
